### ISSUE TITLE
Refactor setting/config handling

### ISSUE THREAD

**Issue by at-wat** [pion/webrtc-v3-design#16]
## Problem

To handle default value of the setting, v2 API uses pointer to primitive types to represent the field is unset.

https://github.com/pion/webrtc/blob/cd3beeab248d81328ff76eeb575c6e28ce240770/settingengine.go#L18-L28
```go
type SettingEngine struct {
	...
	timeout struct {
		ICEDisconnectedTimeout    *time.Duration
```
There is a setter
https://github.com/pion/webrtc/blob/cd3beeab248d81328ff76eeb575c6e28ce240770/settingengine.go#L73-L74
```go
func (e *SettingEngine) SetICETimeouts(disconnectedTimeout, failedTimeout, keepAliveInterval time.Duration) {
	e.timeout.ICEDisconnectedTimeout = &disconnectedTimeout
```
, default value const
https://github.com/pion/ice/blob/3b9a98917766765015c8d34db37db50c80760ef6/agent_config.go#L18
```go
	defaultDisconnectedTimeout = 5 * time.Second
```
, pointer field in subpackage config struct
https://github.com/pion/ice/blob/3b9a98917766765015c8d34db37db50c80760ef6/agent_config.go#L51-L73
```go
type AgentConfig struct {
	...
	DisconnectedTimeout *time.Duration
```
and `nil` check.
https://github.com/pion/ice/blob/3b9a98917766765015c8d34db37db50c80760ef6/agent_config.go#L180-L184
```go
	if config.DisconnectedTimeout == nil {
		a.disconnectedTimeout = defaultDisconnectedTimeout
	} else {
		a.disconnectedTimeout = *config.DisconnectedTimeout
	}
```

This structure makes default value handling complex.

## Solution

One of the possible solution is using the Functional Option Pattern. 
In this example, it makes fields of `ice.AgentConfig` struct non-pointer type and makes default value handling much simpler.
In this case, `webrtc.SettingEngine` will receive the list of functional options from caller and pass directly to `ice.NewAgent`.

## Related discussions
- https://github.com/pion/webrtc/issues/872

**Comment by at-wat** [comment]
@Sean-Der @enobufs Any thoughts?

**Comment by Sean-Der** [comment]
@at-wat I am in support if you think it is important! I am personally not as passionate about this part of the API, but I am all for you owning it :)

I am pretty focused on fixing PayloadType/SSRC issues with the API. This has been the main issue I have been helping users with. I have had multiple days lost debugging this :(

**Comment by at-wat** [comment]
I think I don't have time to do this soon. This might be a v4 issue unless someone want to take this.

**Comment by Sean-Der** [comment]
Closing for now.

Changing the API doesn't have any immediate benefit for the user, so pushing out for now. If anyone has data on people not being able to build things or a higher bug rate I would love to dig into this more!
