### ISSUE TITLE
Timelines and expectations 

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc-v3-design#17]
No real rush on this, but I would love to set some expectations/ideas around when we should have this done. We are really close to `/v3` and refactoring the API is the biggest thing. We are going to see more and more confused users (and overworked devs) if we don't close the gap.

I don't think all these API changes need to be done. But we should have all the breakage done at least. We can shortly follow up with a `3.1.0` with more great stuff.

What do people think of August 21st? We can totally go over if things come up, but I want to set expectations so that we have a sense of urgency. @adwpc @at-wat @jeremija @tarrencev @lherman-cs (add others that may be involved)

**Comment by adwpc** [comment]
@Sean-Der @at-wat 
Thanks for your aswome design!
V3 is cool! We should do this.
I can help with nack and twcc part according to your design. 
I have free time on weekends.

**Comment by Sean-Der** [comment]
@adwpc that would be amazing, all yours!

I think as soon as we can prove that our new API makes all of the [examples](https://github.com/pion/webrtc-v3-design/tree/master/examples) possible we can merge. I don't want to make any changes to pion/webrtc until we are 100% confident in the new API.

If you have time this weekend it would also be really helpful to if you could do some of the examples using the new V3 API. Maybe you can grab the FEC and TWCC ones? I will start on the other ones.

@at-wat mind if I merge https://github.com/pion/webrtc-v3-design/pull/12 ?

**Comment by at-wat** [comment]
> @at-wat mind if I merge #12 ?

Fixed document error. Sure, please merge it.

**Comment by lherman-cs** [comment]
@Sean-Der I've been really busy with personal life stuff lately, so I probably can not contribute in the near future... But will definitely contribute.
