### ISSUE TITLE
Users shouldn't have to manage PayloadType/SSRC themselves

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc-v3-design#2]
I see lots of people make errors because they send the wrong PayloadType and SSRC. In general I don't want users to have to manage this anymore.

When a user creates a `LocalTrack` and they are feeding it locally (from a file on disk) they shouldn't have to worry about these values.

**Comment by at-wat** [comment]
In WebAPI, it seems done in the layer of RTCRtpReceiver and RTCRtpSender.

https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpReceiver#Methods
> ### `RTCRtpReceiver.getParameters()`
>    Returns an `RTCRtpParameters` object which contains information about how the RTC data is to be decoded.

https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender#methods
> ### `RTCRtpSender.getParameters()`
>    Returns a `RTCRtpParameters` object describing the current configuration for the encoding and transmission of media on the track.
> ### `RTCRtpSender.setParameters()`
>    Applies changes to parameters which configure how the track is encoded and transmitted to the remote peer.

Parameters given to `setParameters` contain encoding information and `codecPayloadType` value.
https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSendParameters

related discussion: https://github.com/pion/mediadevices/issues/146

**Comment by at-wat** [comment]
Original spec

- Sender.GetParameters: https://w3c.github.io/webrtc-pc/#dom-rtcrtpsender-getparameters
- Sender.SetParameters: https://w3c.github.io/webrtc-pc/#dom-rtcrtpsender-setparameters
- Receiver.GetParameters: https://w3c.github.io/webrtc-pc/#dom-rtcrtpreceiver-getparameters

https://w3c.github.io/webrtc-pc/#dom-rtcrtpcodecparameters
```
dictionary RTCRtpCodecParameters {
  required octet payloadType;
  required DOMString mimeType;
  required unsigned long clockRate;
  unsigned short channels;
  DOMString sdpFmtpLine;
};
```

**Comment by Sean-Der** [comment]
I feel good about this! We deal with parameters only now. Users don't have to deal with SSRC/PayloadType at all now.
