### ISSUE TITLE
Does SettingEngine need to be an interface?

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc-v3-design#29]
Pro
- Prevents us from accidentally adding public fields (everything should be a method)

Con
- Creates indirection in the code (need to have struct and interface)
- Migration will be frustrating. People commonly do `var s webrtc.SettingEngine`, so this change will not be a compile error. However the code will then crash at runtime

**Comment by Sean-Der** [comment]
@at-wat my vote is that it should be a struct. I am fine with making all other public objects interfaces though! (PeerConnection, RTPSender, RTPReceiver etc...)

Anything that is for configuration `RtpTransceieverInit` should stay a struct though. Readability wise I think it is important that we match the browser API.

**Comment by Sean-Der** [comment]
I moved it in da17e6afc484ba18670d44d1db3816348d864227

If there is a strong reason for it I am in favor. However I think there is a high risk of impacting `/v2` users negatively.

**Comment by at-wat** [comment]
I just defined that as an interface to make API design without explicit struct members. I don't think it's needed to be an interface.

**Comment by Sean-Der** [comment]
:+1: nice, resolving :)
