### ISSUE TITLE
Migration notes and 'Media API' design doc

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc-v3-design#33]
Pion WebRTC has a completely re-designed media API. We have collected data and feedback after two years of usage. These are the use cases we wanted to support that Pion v2 wasn't able to do.

####  Easy Error Concealment
Pion WebRTC /v3 make error concealment patterns like FEC and NACK easy. Using a public API you can specify your own algorithms, or use the ones we provide. Pion provides the flexibility so you can choose what is best for your application.

#### Easy Congestion Control
Designed to be pluggable as well. Pion allows you to specify your own algorithm, or use the ones we provided.

#### Codecs for a track can be chosen at signaling time
We now allow you to choose what codec a track represents at signaling time. A track can either be a single codec, or it can change depending on what the remote candidate supports. This allows `pion/mediadevices` to act more like the browser, you don't need to specify a codec when creating the PeerConnection.

#### Remove PayloadType and SSRC from Public API
You no longer have to worry about juggling PayloadTypes and SSRCes. Pion now handles this internally, you just set the codec and go.

#### Allow fan out, but still support per-track messages
Pion WebRTC /v2 made massive changes to the media API to support fan out. You can send one video packet to multiple PeerConnections. Unfortunately it wasn't easily possible to then send message to a single PeerConnection. This made NACKs very hard to implement. We now have an API that supports all of this.

####  MediaEngine has been removed.
Everything is now driven via the SettingEngine. All the existing options still exist.

We have three new options `SetEncodings`, `SetTrackLocalAdapters` and `SetTrackRemoteAdapters`

`SetEncodings` allows you to specify what codecs you support. This informs the remote peer what you are willing to accept, and what you may send.

```
s.SetEncodings([]*webrtc.RTPCodecCapability{        
        {
            MimeType:  "video/vp8",
            ClockRate: 90000,
        },
        {
            MimeType:  "video/h264",
            ClockRate: 90000,
        },
})
```

`SetTrackLocalAdapters` and `SetTrackRemoteAdapters` allow you to set a list of adapters that happen when sending and receiving media. We provide adapters to do common tasks in tree. These include Applying FEC, Sending/Responding to NACKs and generating Transport Wide Congestion Control Reports.

```
s.SetTrackRemoteAdapters([]*webrtc.TrackRemoteAdapter{        
       remoteadapter.NewTransportWideCongestionControlGenerator(),
       remoteadapter.NewJitterBuffer(),
})  
```

You can also define your own adapters to implement any behaviors you wish.

#### `AddTrack` was removed. Pion only has Transceiver based API.
The WebRTC API has gone through three iterations. You can read about that [here](https://blog.mozilla.org/webrtc/the-evolution-of-webrtc/). AddTrack is just an abstraction on top of newer APIs.

We have decided to remove `AddTrack` to make things clearer. You should instead use `AddTransceiverFromTrack` or `AddTransceiverFromKind`

#### Track is now an interface
Users can now define their own tracks. This allows users to choose the codec the track represents at run-time and set other custom behavior.

A Track could actually be multiple feeds with different codecs. This also gives us the flexibility to allow sending Simulcast. We have two pre-made `Track` implementations. `NewStaticLocalSampleTrack` and `NewStaticLocalRTPTrack`. Existing code will be very easy to port to this.

#### `Sample` now computes `Samples` for you
The `Sample` API required users to do time math. This caused lots of bugs, and people found it confusing. We have instead exposed `Duration` which does these conversions internally.

**Comment by Sean-Der** [comment]
@TannerGabriel @tarrencev @jeremija @jinleileiking @OrlandoCo @tarrencev @billylindeman @leewardbound @lherman-cs @steebchen @sgotti @at-wat @adwpc 

What do you think? This handles all the use cases I have collected. I will work on expanding the design doc, but this is the direction it is going. I think we can finish this repo this weekend, and then I will start a branch in `pion/webrtc`

You can see the API in action in [examples](https://github.com/pion/webrtc-v3-design/tree/master/examples). We have also been writing shims to show the usage.

After that is done I and merged I feel that taging `v3.0.0` is warranted. All other fixes/changes on the horizon don't break the public API.

**Comment by tarrencev** [comment]
I love these changes!

**Comment by jeremija** [comment]
Me too, I really like the direction `pion/webrtc` is heading!

**Comment by jech** [comment]
> Remove PayloadType and SSRC from Public API

Could you please explain what that means?  Will applications that want to control the SSRC still be able to?

> SetTrackLocalAdapters and SetTrackRemoteAdapters allow you to set a list of adapters that happen when sending and receiving media. We provide adapters to do common tasks in tree. These include Applying FEC,

Is the FEC applied by the application or by the library?  If the former, how does the application attach FEC to a data packet (I assume you're implementing flexible FEC).  If the latter, how does the application instruct the library about the amount of FEC to apply?  Is the application able to use different amounts of FEC on different tracks and vary the amount of FEC over time?

**Comment by lherman-cs** [comment]
Like it too 😊!

**Comment by TannerGabriel** [comment]
Also, really like the direction Pion is heading!

**Comment by Sean-Der** [comment]
@jech 

> Could you please explain what that means? Will applications that want to control the SSRC still be able to?

Yes! `webrtc.Track` is an interface, so you can provide your own implementation. We also provide some in-tree ones that set the right SSRC/PayloadType for the codec you choose https://github.com/pion/webrtc-v3-design/blob/master/webrtc/pkg/media/track.go#L36 or you just need satisfy the [interface](https://github.com/pion/webrtc-v3-design/blob/master/webrtc/track.go#L56)

> Is the FEC applied by the application or by the library? 

Either. The SettingEngine allows you to specify interceptors. You can use the in-tree ones. I don't know what we will provide yet, but since they are opt-in we can provide many versions/settings.

You can also easily write your own! They are just simple I/O functions. You can have multiple if you want also.

**Comment by jech** [comment]
Where will the WriteRTP method live?  On Track, or on Sender?
