### ISSUE TITLE
How do users implement the internal pipeReader/pipeWriter?

### ISSUE THREAD

**Issue by lherman-cs** [pion/webrtc-v3-design#35]
Currently, the local RTP track interface requires the implementor to have a "write" method, and we'll get the rtp packet through internal pipe (push model):

https://github.com/pion/webrtc-v3-design/blob/77d178fb5d71c44c4d019917890119f87b914726/webrtc/trackrtp.go#L38-L63

Since `pipeReader` is internal only, how do users implement this or be aware of this internal detail? Also, wouldn't it be better to change `rtpengine.Writer` to `rtpengine.Reader` if the users need to convert from push to pull model anyways?

@at-wat @Sean-Der any thoughts? I might've missed something here..

**Comment by at-wat** [comment]
It should be used only between TrackLocalRTP and RTPSenderPassthrough.
As RTPTrack is a pion's extension (in WebRTC spec, media encoding is in RTPSender but we don't want to), there is no generic way to connect random pair of TrackLocal and RTPSender.
So, in my intention, TrackLocalRTP and RTPSenderPassthrough should be implemented in the same package and connected by the package internal pipe.

**Comment by Sean-Der** [comment]
@lherman-cs but these are my thoughts when digging through everything again! Sorry this spans multiple issues, but this seems like a good place :) I think we have a collection of downright **amazing** ideas. Stuff that I wish I had realized 3 years ago. These are my highlights.

---

These are the 'golden' concepts in the designs.

### Make Track an interface
We can provide multiple implentors in-tree
* Static Track. Pre-set codec we can call `SetParameters` to notify users of the SSRC/PayloadType
* Dynamic Track. We can call `SetParameters` and users can choose the codec they want.
* We can let users have a RTP Track OR one that does `EncodedFrame`. But internally Pion only knows RTP
* Users can bring their own codecs now. We just deal with setting SSRC/PayloadType. They push RTP and we don't care.

`pion/mediadevices` can also generate a `Track`. You can be either codec, and you can satisfy the W3C API!

### Interceptors

A PeerConnection can have a list of `Interceptors` that process all incoming/outgoing RTP and RTCP packets. These can either be set by the users, or they can use ones we have in-tree.

This solves

* FEC. Outgoing interceptor modifies the stream and applies it.
* JitterBuffer. Incoming interceptor applies delay and can generate NACKs
* NACK Responder. Outgoing interceptor processes RTCP before it goes to the user
* REMB. Incoming interceptor can send back bitrate suggestions based on loss
* TWCC. Incoming interceptor can send back stats.

---

I think we can simplify what we have.

* We don't need to modify `RTPSender` or `RTPReceiver`

* We put the Interceptors on SettingEngine we need two types. Maybe a interceptor has a enum?
  - Global interceptor (keep streams in sync)
  - Single stream interceptor (apply FEC)

* We need two types of `Track` `TrackLocal` and `TrackRemote`

* `TrackRemote` stays a struct, and retains the API it has today. I am not aware of any API issues.

* `TrackLocal` is an interface. It gives
    - `id` and `label`. A unique ID for the track, and then the `container` it belongs too.
    - A way to choose your codec
    - Information around that codec (PayloadType, SSRC)

```
// Passed as an argument to Bind/Unbind
type TrackLocalContext struct {}

// Streams so the track can Send RTP/RTCP. Also information around the values needed for RTP/RTCP
func (t *TrackLocalContext) RTPStream () io.Writer {} 
func (t *TrackLocalContext) RTCPStream () io.Writer {} 
func (t *TrackLocalContext) RTPParameters() RTPParameters {}

type TrackLocal interface {
    ID() string
    Label() string

    // Called by the PeerConnection. This function is what 'Starts' the track. The PeerConnection passes in
    // - Codecs (and the PayloadType/SSRC of them)
   // -  Handles to write RTP/RTCP
    Bind(TrackLocalContext) error
    Unbind(TrackLocalContext) error
}
```

We can then have multiple instances of `TrackLocal` that fit all the use cases. For `EncodedFrame` and `RTP` Tracks you will have one. 

```
type TrackLocalStatic struct { 
  TrackLocalContext
}

NewTrackLocalStatic(requestedCodec) *TrackLocalStatic {}

func (t *TrackLocalStatic) Bind(....) error {
   // Assert that codec exists
   // Copy the PayloadType/SSRC
   // copy TrackLocalContext
}

func (t *TrackLocalStatic) Write(in) error {
   // Update in with proper PayloadType/SSRC
   return t.RTPStream().Write(in)
}
```

For a user to use this it would look like

```
track := media.NewTrackLocalStatic("h264", "profile-id=....")
peerConnection.AddTransceiverFromTrack(track)
```

For `GetUserMedia` Tracks you will just have a constructor.  Internally all the encoding/packetizing/sending is happening without the user knowing about it

```
type GetUserMediaLocalTrack struct {}

NewGetUserMediaLocalTrack(constraints) *TrackLocalStatic {}

func (t *TrackLocalStatic) Bind(t TrackLocalContext) error {
   // Assert that codec exists
   // Copy the PayloadType/SSRC

   go func() {
     // Pull video frame
     // Packetize video frame
     t.RTPStream().Write(rtpPacket)
  }()
}
```

For a user to use this it would look like

```
stream := mediadevices.GetUserMedia()
for t := range stream.Tracks() {
    peerConnection.AddTransceieverFromTrack(t)
}
```

**Comment by Sean-Der** [comment]
@at-wat what do you think? Do you think simplification is possible? I think we can accomplish all our use cases, and bring down the complexity

**Comment by lherman-cs** [comment]
I'm a bit confused. I'm not sure what should go in the "Write" implementation from local tracks.

In the mediadevices case, the local track only knows how to get the data from the source and package it in RTP format. But, it doesn't know how to "write" since it doesn't know anything about webrtc's peerconnection. 

Should Bind give TrackLocal access to write the rtp packets? Also, since the data needs to be pushed from the users, would that happen in `Bind`?

**Comment by Sean-Der** [comment]
@lherman-cs by default we will not have a `Write`, but an implementor could add one. I think this captures the design, but maybe makes it a little simpler? If I am missing use cases @at-wat please correct me :)

For `EncodedFrame` and `RTP` Tracks you will have one. 

```
type TrackLocalStatic struct { 
  rtpOut, rtcpOut //Not sure what these look like yet
}

NewTrackLocalStatic(requestedCodec) *TrackLocalStatic {}

func (t *TrackLocalStatic) Bind(....) error {
   // Assert that codec exists
   // Copy the PayloadType/SSRC
   // Initialize rtpOut/rtcpOut
}

func (t *TrackLocalStatic) Write(in) error {
   // Update in with proper PayloadType/SSRC
   return t.rtpOut.Write(in)
}
```

For `GetUserMedia` Tracks you will just have a constructor.  Internally all the encoding/packetizing/sending is happening without the user knowing about it

```
type GetUserMediaLocalTrack struct { 
  rtpOut, rtcpOut //Not sure what these look like yet
}

NewGetUserMediaLocalTrack(constraints) *TrackLocalStatic {}

func (t *TrackLocalStatic) Bind(....) error {
   // Assert that codec exists
   // Copy the PayloadType/SSRC
   // Initialize rtpOut/rtcpOut

   go func() {
     // Pull video frame
     // Packetize video frame
     t.rtpOut.Write(rtpPacket)
  }()
}
```

**Comment by Sean-Der** [comment]
@at-wat @lherman-cs I updated my comment with the following

* Added `TrackLocalContext` so we don't need to break API when we add new features
* Added `Unbind` every time a `LocalTrack` is stopped or removed from a `PeerConnection` that will be fired.

**Comment by Sean-Der** [comment]
@at-wat @lherman-cs If you don't seen any problems will roll forward with this during the weekend, thanks :) 

After this lands I feel good enough to start `v3-media` in `pion/webrtc`

**Comment by lherman-cs** [comment]
@Sean-Der how does the offer include available codecs if we never tell PeerConnection? Or do we still need to populate the setting engine?

**Comment by Sean-Der** [comment]
@lherman-cs I think we should default to everything on, and then people can turn stuff off via SettingEngine.

I also would be up for making it explicit. We can default to none and users MUST do `webrtc.DefaultRTPCodecs`. I think boilerplate like that is fine, it helps introduce people to the SettingEngine. People have a hard time discovering it, but when they do they are really happy.

**Comment by lherman-cs** [comment]
@Sean-Der oh another thing, can Track assume that `Bind` is only called once, and can only be called again after `Unbind`? For example, can `Track` be consumed by multiple `PeerConnection`?

**Comment by Sean-Der** [comment]
A track can be called with `Bind` multiple times. You can do a SFU/fan-out that way

```
                                                                --------> Viewer PeerConnection
                                                                |
In PeerConnection --> (Copy Buffers) Track ---> Viewer Peerconnection
                                                                |
                                                                --------> Viewer PeerConnection
```

**Comment by lherman-cs** [comment]
I see, so I guess in that case LocalTrackContext will have a PeerConnection ID so that the implementor can know which goroutine (inside of Bind that pushes the media data) that needs to be torn down?

I guess it doesn't need to be an ID, as long as we receive the same PeerConnection in Unbind.

**Comment by Sean-Der** [comment]
@lherman-cs yea! Each PeerConnection does have a Unique ID, but I am happy giving `Bind` any state it needs to make this easier

* PeerConnection
* RTPSender
* PeerConnection id only 

I would even maybe generate my own unique id (and put things in a map) and remove on `Unbind`?

**Comment by lherman-cs** [comment]
@Sean-Der Sweet, that makes sense. Are you starting a new branch? Because I'm also working on rewriting some of mediadevices APIs to reflect the new changes, so it would be nice if I could already use the interfaces 😃!

**Comment by Sean-Der** [comment]
The Track API is done! By going with `Bind/Unbind` I was able to satisfy all the APIs.

After `Interceptors` are done we will come back and simplify.
