### ISSUE TITLE
About nack, jitter buffer, replay protection and transportcc

### ISSUE THREAD

**Issue by masterada** [pion/webrtc-v3-design#36]
We have finaly managed to put together nack, jitter bugger and transportcc. I'm going to share our discoveries and some code.

## Our scenario

There is a simple broadcaster who sends the stream from the browser to a pion server. We then pack the stream as webm and send it to ffmpeg for transcoding. We send back transportcc to the browser, and handle incoming nack requests. There is also a jitter buffer.

A single user can connect to this broadcaster to see the stream in low latency instead of the transcoded hls stream. In this case, instead of sending our own transportcc, we use the transportcc from this user. We also handle nack requests coming from this user.

### Jitter buffer in proxy mode
The most imprtant think we found, is when we use pion as a proxy (forwarding packets from above broadcaster to the connected user), is that jitter buffer completely destroys transportcc. When we enabled the jitter buffer in this case, transportcc scaled the stream to 0, eventually dropping the stream altogether. This is because the jitter buffer greatly influences the total transmission time of the packets (from broadcaster to user).

### Nack in receiver mode vs replay protection
In order for nack to work, the replay buffer size had to be adjusted to be at least the size of the receive_log (see code below). The 64 default might not be a good idea once nack is implemented in pion.

## Code samples

- nack, jitter buffer, sequence unwrapper
   - see: https://github.com/pion/example-webrtc-applications/pull/67
- transportcc
   - this is a bit more complicated to extract from our code, and i'm waiting for the collague who wrote it

**Comment by Sean-Der** [comment]
Wow this is amazing data! Thank you so much @masterada this is a truely transformational contribution. I really appreciate it. The immaturity in this area hurts Pion the most. If you are interested I would love to work closely with you (and your team) on moving the `Interceptors` pattern forward.

https://github.com/pion/webrtc-v3-design/issues/34 is that issue. What do you think?
