### ISSUE TITLE
FEC Support

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc-v3-design#5]
Do we provide this as part of `pion/rtp`, and allow users to configure things as they please?

I have heard in a few cases that using FEC and no JitterBuffer at all is a much experience for users. Then in conjunction with TWCC you can measure loss and adjust FEC as needed.

**Comment by adwpc** [comment]
Agree.
FEC and JB each has its own advantages and disadvantages.
FEC is simple and JB(BWE+PLI+NACK+FEC+BUFFER+...) is complex.

FEC has a lower latency but more bandwidth useage, it is better when the user bandwidth is not a bottleneck
Nack has a little bandwidth useage but more latency, it is better when  the user bandwidth is a bottleneck

**Comment by adwpc** [comment]
There are two fec: ulpfec and flexfec. defalut is ulpfec.
about ulpfec, must support red and rtx first:
```
a=rtpmap:114 red/90000
a=rtpmap:115 rtx/90000
a=fmtp:115 apt=114
a=rtpmap:116 ulpfec/90000
```
![image](https://user-images.githubusercontent.com/12995347/89099784-55b41d80-d424-11ea-9d89-332cbe6f7abe.png)

**Comment by adwpc** [comment]
Doing some research about ulpfec.

**Comment by Sean-Der** [comment]
I feel good about this! The `passthrough` pattern allows us to transform data and send additional things (like RTCP)

#34 is my only out standing question

@adwpc I think the rest is more implementation detail. With the 'passthrough' pattern described in https://github.com/pion/webrtc-v3-design/issues/33 a user could generate the new packets as they wish! I think we should ship the primitives, and then in follow up releases we can ship little helpers that people can use as they wish.
